### ISSUE TITLE
Fail to download the dataset

### ISSUE THREAD

**Issue by MercerSU** [ctu-mrs/slam_datasets#1]
Hi, thank you for open-sourcing this dataset. However, following the provided download methods, I couldn't successfully download it.I tried all the methods to access this website "https://nasmrs.felk.cvut.cz/ "but none were successful. Has the website been closed? Could you provide an alternative download link? Thank you so much.

**Comment by klaxalk** [comment]
I'm sorry, our storage got cut out of the web because of recent cyber attacks at our university. We are currently solving the issue. In the meantime, what particular dataset are you interested in?

**Comment by MercerSU** [comment]
Sorry to hear that. Hopefully you can resolve it smoothly. Additionally, I'm quite interested in the Forest dataset within slam_datasets,and I would greatly appreciate it if there were alternative download methods available.Thank you for the response.

**Comment by klaxalk** [comment]
Hey, the original link is working now.

**Comment by MercerSU** [comment]
It worked. Thank you!
